services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
    container_name: backend-elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elasticnet
    volumes:
      - esdata:/usr/share/elasticsearch/data

  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: backend-web
    depends_on:
      - elasticsearch
    networks:
      - elasticnet
    ports:
      - "8000:8000"
    volumes:
      - ../app:/backend/app
networks:
  elasticnet:
    driver: bridge

volumes:
  esdata: